spring:
  application:
    name: url-shortener-orchestrator
logging:
  level:
    com.cs.urlshortenerorchestrator: DEBUG
    org.springframework: DEBUG
app:
  shortener:
    code-length: 6
    alphabet: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
