package com.cs.urlshortenerorchestrator.analytics.orchestration;

import com.cs.urlshortenerorchestrator.engine.agent.AgentClient;
import com.cs.urlshortenerorchestrator.engine.agent.AgentRole;
import com.cs.urlshortenerorchestrator.engine.agent.BoundedWorkspaceTool;
import com.cs.urlshortenerorchestrator.engine.agent.CodeGenerationResult;
import com.cs.urlshortenerorchestrator.engine.agent.EngineeringAgent;
import com.cs.urlshortenerorchestrator.engine.agent.EngineeringTask;
import com.cs.urlshortenerorchestrator.engine.agent.OpenAiCompatibleAgentClient;
import com.cs.urlshortenerorchestrator.engine.domain.Artifact;
import com.cs.urlshortenerorchestrator.engine.domain.ArtifactType;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.ObjectMapper;

import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

class LiveAnalyticsTestingAgentTest {

    @Test
    void liveTestingAgentGeneratesTestsForExistingAnalyticsImplementation() {

        assumeTrue(
                "true".equalsIgnoreCase(
                        System.getenv("LIVE_AGENT_TESTS")),
                "Set LIVE_AGENT_TESTS=true to run live agent tests"
        );

        assumeTrue(
                System.getenv("LLM_BASE_URL") != null
                        && System.getenv("LLM_MODEL") != null
                        && System.getenv("LLM_API_KEY") != null,
                "Live LLM configuration is required"
        );

        Path projectRoot =
                Path.of(System.getProperty("user.dir"));

        BoundedWorkspaceTool workspace =
                new BoundedWorkspaceTool(projectRoot);

        AgentClient liveClient =
                new OpenAiCompatibleAgentClient(
                        System.getenv("LLM_BASE_URL"),
                        System.getenv("LLM_API_KEY"),
                        System.getenv("LLM_MODEL"),
                        8000
                );

        EngineeringAgent engineeringAgent =
                new EngineeringAgent(
                        liveClient,
                        workspace,
                        new ObjectMapper()
                );

        /*
         * These are CODE artifacts representing the implementation
         * already generated by the live implementation workflow.
         *
         * EngineeringAgent(TESTING) will resolve their storage locations
         * through WorkspaceTool and include the actual source code in
         * the testing-agent context.
         */
        List<Artifact> implementationArtifacts =
                List.of(
                        codeArtifact(
                                "analytics-event",
                                "src/main/java/com/cs/urlshortenerorchestrator/analytics/Event.java"
                        ),
                        codeArtifact(
                                "analytics-event-store",
                                "src/main/java/com/cs/urlshortenerorchestrator/analytics/EventStore.java"
                        ),
                        codeArtifact(
                                "analytics-controller",
                                "src/main/java/com/cs/urlshortenerorchestrator/analytics/AnalyticsController.java"
                        ),
                        codeArtifact(
                                "analytics-application",
                                "src/main/java/com/cs/urlshortenerorchestrator/analytics/AnalyticsApplication.java"
                        )
                );

        /*
         * Fail clearly if somebody runs the live test before the
         * live implementation milestone has generated these sources.
         */
        for (Artifact artifact : implementationArtifacts) {
            assertThat(
                    workspace.exists(
                            artifact.storageLocation()
                    )
            )
                    .as("Expected generated Analytics source to exist: %s",
                            artifact.storageLocation())
                    .isTrue();
        }

        EngineeringTask testingTask =
                new EngineeringTask(
                        AgentRole.TESTING,
                        """
                        Validate the existing greenfield Analytics capability.

                        The implementation is intended to:
                        - accept and retain click events in memory,
                        - retrieve recorded events,
                        - aggregate click counts by shortened URL,
                        - expose the behavior through REST endpoints.

                        Generate focused tests for the behavior that is
                        actually present in the supplied implementation.
                        Tests should also expose meaningful gaps or incorrect
                        behavior rather than assuming missing functionality works.
                        """,
                        implementationArtifacts,
                        List.of(
                                "Use JUnit 5",
                                "Use Spring Boot test support only when useful",
                                "Do not modify production source code",
                                "Prefer unit tests for EventStore and focused controller tests",
                                "Test observable behavior rather than private implementation details",
                                "Generated tests must compile against the current implementation",
                                "Do not invent production methods that do not exist"
                        ),
                        "src/test/java/com/cs/urlshortenerorchestrator/analytics/"
                );

        CodeGenerationResult result =
                engineeringAgent.execute(testingTask);

        assertThat(result.files())
                .isNotEmpty();

        System.out.println();
        System.out.println("Generated Analytics test files:");

        result.files().forEach(file -> {
            System.out.println("  " + file.path());

            assertThat(
                    workspace.exists(file.path())
            ).isTrue();
        });

        System.out.println();
        System.out.println(
                "Testing agent summary: " + result.summary()
        );
    }

    private Artifact codeArtifact(
            String id,
            String path) {

        return new Artifact(
                id,
                ArtifactType.CODE,
                path,
                "implementation",
                "live-implementation-execution",
                path,
                Map.of(
                        "scenario", "GREENFIELD",
                        "feature", "ANALYTICS",
                        "generatedBy", "EngineeringAgent"
                ),
                Instant.now()
        );
    }
}